### ISSUE TITLE
Compatibility with WebSockets 3.0

### ISSUE THREAD

**Issue by TomOudeNijhuis** [housleyjk/aiopyramid#15]
I suppose support for the ConnectionClosed exception needs to be implemented in WebsocketConnectionView. See websockets changelog: https://websockets.readthedocs.org/en/stable/changelog.html

I updated the code as followed:
```python
from websockets.exceptions import ConnectionClosed

@asyncio.coroutine
def __call__(self, ws):
    self.ws = ws
    yield from self.on_open()

    while True:
        try:
            message = yield from self.ws.recv()
            
            if message is None:
                yield from self.on_close()
                break
                
            yield from self.on_message(message)
            
        except ConnectionClosed:
            yield from self.on_close()
            break
```
Would this be a suitable solution?

**Comment by housleyjk** [comment]
That works for the class-based websocket, but it doesn't protect code that uses the function approach. I should have a fix for this out later today.

**Comment by TomOudeNijhuis** [comment]
Thank you very much for your quick response. I will try your new version later today.
