### ISSUE TITLE
aiopyramid incompatibility with pyramid_tm

### ISSUE THREAD

**Issue by dfee** [housleyjk/aiopyramid#26]
In [this comment](https://github.com/housleyjk/aiopyramid/issues/16#issuecomment-179387735) you mentioned that `aiopyramid` is incompatible with `pyramid_tm`. I'd like to explore this a bit more:

It seems that indeed `pyramid_tm` thinks in terms of threads – but `aiopyramid` thinks in terms of both threads and coroutines. My (somewhat ignorant) assumption is that your concern is that `pyramid_tm` will try committing when coroutine views (those defined with `async def` or with the `@asyncio.coroutine` wrapper) finish, but you lack concern for regular (sync) functions.

The problem would then be two-fold (I think):
1. `transaction.commit()` could block in async-code during view teardown (when `pyramid_tm` would execute it) which could very much hurt responsiveness.
2. the `transaction` exists in the scope of all coroutines, which means that we could have some strange half-states in those coroutines that we aren't necessarily ready to commit.

The second problem (easier to tackle) can be handled by only doing transaction work in executors, for instance using the helpful `@use_executor` decorator from `aiopyramid.helpers` module.

The first problem is a bit more difficult. Perhaps there's a way to conditionally exclude `transaction.commit()` from occuring. One idea for this is to write a custom `includeme(config)` for `pyramid_tm` that sets a [discriminator](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.action) on this [line](https://github.com/Pylons/pyramid_tm/blob/master/pyramid_tm/__init__.py#L172) so that `ensure()` is not called if it's a coroutine.

Regardless, your comment seems to imply that thread based concepts shouldn't be intertwined with this framework – that includes using `sqlalchemy.orm.scoped_session`. Though again, if we're careful to only use sessions, transactions, and anything else that's thread-aware in an executor, everything should work fine, right?

**Comment by housleyjk** [comment]
You have it right.

Also, committing based on whether an error occurs in a view is easy using a view callback, which can be done for async views and sync views alike.

The idea of a true ORM is generally incompatible with an async framework, unless the ORM is also itself async. The reason is that an ORM generally abstracts away io so that it's not necessarily clear in the code when the database will be hit, it's conditional on the cache and other things. Also, if I remember right, the creator of sqlalchemy has done the tests (and I verified some of this myself about a year ago) that async db connections are not really any faster than sync ones. So, he is probably not going to make an async version of the ORM. 

My perspective is that if an ORM is really core to your app, then it may be good to separate any async code (websockets) from your application and make two separate apps, one sync and one async using other means of communication (like a redis queue) to share data between them.

**Comment by dfee** [comment]
Basically, my solution in point 2 was wrong – the `discriminator` passed to Pyramid's `config.action` doesn't discriminate whether it should be called, it's simply a name for the action.

In addition, the aiopyramid `view_mapper` isn't called until after the `pyramid_tm` tween has already acted, so there's no way to conditionally create a transaction using that method – the tween will always create one, unaware of what the view function is, or whether a view function is a/sync.

However, we can attack the problem by not including `pyramid_tm` but ripping off the best ideas from it, such as when to `commit` or `abort`.

The better approach then is to create a transaction in sync views (as needed), and use `request.add_finished_callback()` to commit manage the commit as described above. This could be done either through a wrapper (maybe naming it `@transaction`) or adding this to the `__init__` method of a Class Based View.

**Comment by housleyjk** [comment]
`add_finished_callback` is what I have done in the past. The only downside I know of is really that you can't wait to commit a transaction after a view is completed.

**Comment by dfee** [comment]
I'm not sure what you mean by the downside. Do you mean that you can't wait until after the WSGI response has been delivered? I.e. you can only commit before the WSGI response is delivered.

In that context, yes, committing would block the response. Did you mean something else?

**Comment by dfee** [comment]
Here is a view mapper that ought to work. Interested in hearing your thoughts…

```
# Adapted from https://github.com/Pylons/pyramid_tm
import sys
import builtins

from pyramid.settings import asbool
from pyramid.util import DottedNameResolver
from pyramid.tweens import EXCVIEW
import transaction

resolver = DottedNameResolver(None)


def reraise(tp, value, tb=None):
    if value.__traceback__ is not tb:
        raise value.with_traceback(tb)
    raise value


def native_(s, encoding='latin-1', errors='strict'):
    text_type = str
    binary_type = bytes

    if isinstance(s, text_type):
        return s
    if isinstance(s, binary_type):
        return str(s, encoding, errors)
    return str(s)


def create_tm(request):
    if 'tm.active' not in request.environ:
        raise AttributeError('tm inactive for request')
    manager_hook = request.registry.settings.get('tm.manager_hook')
    if manager_hook:
        manager_hook = resolver.maybe_resolve(manager_hook)
        return manager_hook(request)
    else:
        return transaction.manager


def default_commit_veto(request, response):
    """
    When used as a commit veto, the logic in this function will cause the
    transaction to be aborted if:
    - An ``X-Tm`` response header with the value ``abort`` (or any value
      other than ``commit``) exists.
    - The response status code starts with ``4`` or ``5``.
    Otherwise the transaction will be allowed to commit.
    """
    xtm = response.headers.get('x-tm')
    if xtm is not None:
        return xtm != 'commit'
    return response.status.startswith(('4', '5'))


class AbortResponse(Exception):
    def __init__(self, response):
        self.response = response


class TransactionExecutorMapper(AsyncioMapperBase):
    def __call__(self, view):
        if asyncio.iscoroutinefunction(view) or asyncio.iscoroutinefunction(
            getattr(view, '__call__', None)
        ):
            raise ConfigurationError(
                'Coroutine {} mapped to executor.'.format(view)
            )
        view = super().__call__(view)

        def wrapper(context, request):
            settings = request.registry.settings

            old_commit_veto = settings.get('aiopyramid_tm.commit_veto', None)
            commit_veto = settings.get('tm.commit_veto', old_commit_veto)
            activate = settings.get('tm.activate_hook')
            attempts = int(settings.get('tm.attempts', 1))
            commit_veto = resolver.maybe_resolve(commit_veto) \
                if commit_veto else None
            activate = resolver.maybe_resolve(activate) if activate else None
            annotate_user = asbool(settings.get("tm.annotate_user", True))
            assert attempts > 0

            if (
                # don't handle txn mgmt if repoze.tm is in the WSGI pipeline
                'repoze.tm.active' in request.environ or
                # pyramid_tm should only be active once
                'tm.active' in request.environ or
                # check activation hooks
                activate is not None and not activate(request)
            ):
                return handler(request)

            # Set a flag in the environment to enable the `request.tm`
            # property.
            request.environ['tm.active'] = True

            manager = getattr(request, 'tm', None)
            if manager is None:  # pragma: no cover (pyramid < 1.4)
                manager = create_tm(request)
                request.tm = manager
            number = attempts
            if annotate_user:
                if hasattr(request, 'unauthenticated_userid'):
                    userid = request.unauthenticated_userid
                else:  # pragma no cover (for pyramid < 1.5)
                    from pyramid.security import unauthenticated_userid
                    userid = unauthenticated_userid(request)
            else:
                userid = None

            while number:
                number -= 1
                try:
                    manager.begin()
                    # make_body_seekable will copy wsgi.input if necessary,
                    # otherwise it will rewind the copy to position zero
                    if attempts != 1:
                        request.make_body_seekable()
                    t = manager.get()
                    if userid:
                        userid = native_(userid, 'utf-8')
                        t.setUser(userid, '')
                    try:
                        t.note(native_(request.path_info, 'utf-8'))
                    except UnicodeDecodeError:
                        t.note("Unable to decode path as unicode")

                    # aiopyramid: replacing handler call with view call
                    response = view(context, request)

                    if manager.isDoomed():
                        raise AbortResponse(response)
                    if commit_veto is not None:
                        veto = commit_veto(request, response)
                        if veto:
                            raise AbortResponse(response)
                    manager.commit()
                    del request.environ['tm.active']
                    return response
                except AbortResponse as e:
                    manager.abort()
                    del request.environ['tm.active']
                    return e.response
                except:
                    exc_info = sys.exc_info()
                    try:
                        retryable = manager._retryable(*exc_info[:-1])
                        manager.abort()
                        if (number <= 0) or (not retryable):
                            del request.environ['tm.active']
                            reraise(*exc_info)
                    finally:
                        del exc_info  # avoid leak

            return response
        return self.run_in_executor_view(wrapper)
```

I've essentially taken the tween code from `pyramid_tm` and put it in the view mapper. What's notable about this approach is:
1. transaction support exists for views configured with `mapper=TransactionExecutorMapper`
2. the transaction is committed at the view mapper level

Therefore, the transaction is really only available for the view in the view pipeline shown below:

![screen shot 2016-10-17 at 1 14 12 am](https://cloud.githubusercontent.com/assets/262602/19429927/0ae83504-9407-11e6-9224-ea28d8e9c57d.png)

Some ideas on an alternate implementation:
1. pyramid_tm works fine with aiopyramid if you can deny activation by request as described [here](http://docs.pylonsproject.org/projects/pyramid_tm/en/latest/#adding-an-activation-hook).
2. we could get rid of the `retry` concept for transactions, and instead put the transaction.commit() logic inside a `request.add_finished_callback()`.

The first approach seems like the winner, if you can effectively map requests to async views before routing, etc. is done. Maybe there's a Pyramid way to build a route map with callable functions, and check those functions for being coroutines.

**Comment by dfee** [comment]
I think I've found an even better (and easier) solution. The problem (again) with `pyramid_tm` is that it can block on IO, which is a bummer for every other coroutine on the event loop.

However, a sqlalchemy session is not bound to the transaction until it's accessed. So, I've done done the following to ensure that I won't ever do that.

in my Pyramid's `main`, immediately after creating a `Configurator` (typically line 1), I issue:
```
config.registry['master_loop'] = asyncio.get_event_loop()
config.include('myproj.models')
```

My `myproj.models` looks like:
```
import asyncio
from sqlalchemy import engine_from_config

from .base import (
    Base,
    BaseModel,
    Session,
)

from myproj.utils import BlockingException
# class BlockingException(Exception):
#     pass


def bind_engine(settings):
    engine = engine_from_config(settings, prefix='sqlalchemy.')
    Session.configure(bind=engine)
    Base.metadata.bind = engine


def db(request):
    if asyncio.get_event_loop() == request.registry['master_loop']:
        raise BlockingException(
            "You tried to create a database session from within async code."
        )

    return Session()


def includeme(config):
    config.registry['master_loop'] = asyncio.get_event_loop()
    bind_engine(config.registry.settings)
    config.add_request_method(db, name='db', reify=True)
```

This effectively ensures that I'll never call my DB from asyncio code (as long as it's accessed via `request.db`). I'm contemplating how to let my `pshell development.ini` retain access.

**Comment by dfee** [comment]
This is my `setup()` for `pshell` as discussed [here](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#extending-the-shell):

```
import asyncio
import signal
from threading import Thread

import myproj.models


def spawn_background_aio(loop):
    def background(loop):
        asyncio.set_event_loop(loop)
        loop.run_forever()

    def stop():
        loop.stop()

    loop.add_signal_handler(signal.SIGALRM, stop)
    t = Thread(target=background, args=(loop,))
    t.start()
    return t


def setup(env):
    # import ipdb; ipdb.set_trace()
    env['master_loop'] = asyncio.get_event_loop()
    env['aio_thread'] = spawn_background_aio(env['master_loop'])
    asyncio.set_event_loop(asyncio.new_event_loop())
    env['db'] = env['request'].db
    env['models'] = myproj.models
```

**Comment by dfee** [comment]
It should also be noted that using `pyramid_tm` the following addition to your `settings.ini` is also necessary (if `request.user` is IO backed):
```
# Because tm.annotate_user gets the unauthenticated_userid, it will block
# the async loop.
tm.annotate_user = false
```

Otherwise, you'll block on IO while pyramid_tm attempts to load the user.

**Comment by housleyjk** [comment]
That's good to know. I had never delved into trying to make pyramid_tm work since I didn't need it. Thank you for checking into this!

**Comment by dfee** [comment]
A couple things worth mentioning after hours of debugging and almost throwing `pyramid_tm` back out.

1. you really don't want a scoped session with `aiopyramid`.
2. you really don't want a ThreadTransactionManager with `aiopyramid`.

Details:
[1] Scoped sessions seem great, but they get very tricky very quickly. Perhaps you could get it to work, but managing a session with a transaction manager is a better practice.

[2] A `ThreadTransactionManager` (i.e. `transaction.manager`) is bad news with `aiopyramid` because the transaction in your views will run in a separate thread (an executor) and any changes you make to the DB session won't be seen when the `pyramid_tm` `tween` wrapper finishes up. Instead the `pyramid_tm` `tween` will call `transaction.commit()` on the transaction in its thread – the Main Thread.

So the workaround is to `transaction.TransactionManager` instead of `transaction.TransactionThreadManager`. Here's how you do it:

In your `config.ini` add the following:
```
# Because tm.annotate_user gets the unauthenticated_userid, it will block
# the async loop. Disable it.
tm.annotate_user = false
tm.manager_hook = myproj.transaction.manager_hook
```

The second directive is important because we're going to override the `transaction.manager` (the default, which is actually an instance of `transaction.ThreadTransactionManager`) with a `transaction.TransactionManager` (not-thread scoped).

The `myproj/transaction.py` file is quite simple:
```
import transaction


def manager_hook(request):
    return transaction.TransactionManager()
```


Then, in your `models/__init__.py` file:
```
import asyncio
from sqlalchemy import (
    engine_from_config,
    event,
)
from sqlalchemy.orm import (
    mapper,
    sessionmaker,
)
from zope.sqlalchemy import register

from myproj.utils import ensure_executor
from .base import Base


def includeme(config):
    engine = engine_from_config(config.registry.settings, prefix='sqlalchemy.')
    maker = sessionmaker()
    maker.configure(bind=engine)
    Base.metadata.bind = engine

    # Put the Main Thread's loop in config for @ensure_executor
    config.registry['primary_loop'] = asyncio.get_event_loop()
    config.registry['dbsession'] = maker  # optional, your needs may vary

    @ensure_executor
    def get_session(request):
        session = maker()
        register(session, transaction_manager=request.tm)
        return session

    config.add_request_method(get_session, name='db', reify=True)
```

Notice how we're deferring registering the session with the transaction_manager until we create it. This seems to be a nuance of using `zope.sqlalchemy.register` with `transaction.TransactionManager` instead of `transaction.ThreadTransactionManager`.

Also note that we're passing an extra keyword argument to register: `request.tm`. We want `zope.sqlalchemy` to use the `transaction` on the request – the one that gets created in the `transaction.py` file.

The file with `@ensure_executor` looks like this:
```
import asyncio
from functools import wraps


class BlockingException(Exception):
    pass


def ensure_executor(f):
    @wraps(f)
    def with_executor(request, *args, **kwargs):
        try:
            loop = asyncio.get_event_loop()
        except RuntimeError:
            pass
        else:
            if loop == request.registry['primary_loop']:
                raise BlockingException(
                    "You tried to call a blocking function from within the"
                    "main thread. Run this function in an executor instead."
                )
        return f(request, *args, **kwargs)
    return with_executor
```

Good luck out there.

**Comment by dfee** [comment]
I've revised the implementation of `@ensure_executor` here: https://github.com/housleyjk/aiopyramid/issues/28

As for accessing the db in `pshell`, you'll probably want to manually create a transaction for the request before calling the DB. This is because the tweens aren't running in `pshell`, so `request.tm` won't exist.

Simply:
```
def setup(env):
    env['request'].tm = transaction.TransactionManager()
    env['db'] = env['request'].db
    env['m'] = myproj.models
```

**Comment by dfee** [comment]
A decorator that might come in handy when using @use_executor to get a transaction to work in:

```
import functools

import transaction
from pyramid.request import Request
from zope.sqlalchemy import register


def with_transaction(f):
    '''Can be used on functions accepting `request` as their first argument or
    class instances with a `request` attribute.'''

    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        # import ipdb; ipdb.set_trace()
        if isinstance(args[0], Request):
            request = args[0]
        elif isinstance(getattr(args[0], 'request', None), Request):
            request = args[0].request
        else:
            raise ValueError(
                'Request must be the first argument or on the instance as '
                'myinstance.request'
            )
        session = request.registry['db_maker']()
        tm = transaction.TransactionManager()
        register(session, transaction_manager=tm)
        result = f(*args, **kwargs, session=session, tm=tm)
        tm.commit()
        session.close()
        return result
    return wrapper
```

I hope this helps someone who comes after me!
