### ISSUE TITLE
Sending Websocket messages to other clients

### ISSUE THREAD

**Issue by dmitrykrylov** [housleyjk/aiopyramid#27]
I am only getting started with websockets and asyncio, that's why I will allow myself to ask for help with the next issue.

I am trying to implement webRTC video chat with aiopyramid and websockets on backend. My frontend exactly is like one in this article: [link](https://shanetully.com/2014/09/a-dead-simple-webrtc-example/).
It connects with the view from docs:

```
@view_config(route_name='echo', mapper=WebsocketMapper)
@asyncio.coroutine
def echo(ws):
    while True:
        message = yield from ws.recv()
        if message is None:
        	break
        yield from ws.send(message)
```

I expect that when I send description to the server I get it on another client. But when I have got gotDescription callback on a client, I get multiple gotIceCandidate callbacks and multiple messages yielded by the view while another client gets nothing.

Logs on the client:
![1111111111111](https://cloud.githubusercontent.com/assets/14343880/19498295/c019deb8-9598-11e6-9e1a-93a88957cd3f.png)

**Comment by housleyjk** [comment]
Can you give me a link to the actual code? The link in that article doesn't go to code that matches the function definitions in the article, so I am wondering if there are discrepancies.

Also, the server in that article has a broadcast function, but the `Aiopyramid` code you sent me doesn't broadcast, it only responds to it's own client. In other words, your Python code isn't sharing messages with other clients. You need to write the equivalent of
``` javascript
wss.broadcast = function(data) {
    for(var i in this.clients) {
        this.clients[i].send(data);
    }
};
```

**Comment by dmitrykrylov** [comment]
Thanks.
Creating a global list of websockets works for me. It's enough for getting started.
