### ISSUE TITLE
aiohttp.wsgi is deprecated

### ISSUE THREAD

**Issue by jgelens** [housleyjk/aiopyramid#30]
It seems GunicornWebWorker from https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/worker.py
needs to be used in the future. I'll see if I can update the custom worker in aiopyramid later.

**Comment by housleyjk** [comment]
Great. Thank you!

**Comment by eddyekofo94** [comment]
@jgelens is it updated? if not how can I work around this? thank you :)

**Comment by jgelens** [comment]
No aiohttp doesn't have wsgi support anymore, so a new lib needs to developed. 
A workaround for now would be pinning to an older version of aiohttp or use uwsgi.

**Comment by eddyekofo94** [comment]
@jgelens which aiohttp version is that? totally new in the python world. Thank you

**Comment by jgelens** [comment]
Got a project running with aiohttp==0.21.6.

**Comment by eddyekofo94** [comment]
@jgelens Thank you very much it finally works. 👍

**Comment by housleyjk** [comment]
The version restriction is on pypi now.
