### ISSUE TITLE
Support for last aiohttp releases?

### ISSUE THREAD

**Issue by tflorac** [housleyjk/aiopyramid#32]
Hi,
I've built an application (WebSockets server) using GUnicorn / Pyramid / aiopyramid stack.
But last aiohttp releases (2.x) doesn't provide WSGI protocol handler anymore and (AFAIK) is not compatible with aiopyramid.
Is there any (simple) way or any plan to make them usable together?

Best regards,
Thierry

**Comment by housleyjk** [comment]
At this point I am not sure how difficult it would be. However the websocket support is better in `aiohttp` now, so I can probably get rid of `ws` and upgrading to the latest `aiohttp` should be mostly a matter updating how we interact with the GunicornWebWorker.

**Comment by tflorac** [comment]
That would be really nice!
I actually really like aiopyramid API  and Pyramid integration, and I will have to find a solution in the next weeks, so having a more precise idea about this would be really great!!  ;)

**Comment by housleyjk** [comment]
@tflorac The master branch should now support recent aiohttp with gunicorn including websockets. Please try it out and let me know if it works for your project.

**Comment by tflorac** [comment]
I made a checkout of your repository, restarted a buildout and my project seems to work without any modification (just had to update packages versions). Great work!
To you plan to make a new release on Pypi soon?

**Comment by housleyjk** [comment]
Since it works for you too, I've made a new release on Pypi. Best of luck!
