### ISSUE TITLE
Request error when submitting forms (gunicorn)

### ISSUE THREAD

**Issue by AnderUstarroz** [housleyjk/aiopyramid#5]
I'm running my app with **gunicorn**,  and when I try to submit a form I'm getting:
 ```
TypeError: object of type 'generator' has no len()
```
 It seems to be related with how the **aiohttp** package handles the request.

Using following packages:
* aiohttp (0.14.1)
* aiopyramid (0.3.0)
* greenlet (0.4.5)
* gunicorn (19.1.1)

**Comment by housleyjk** [comment]
This should be fixed in the latest code feb104cd0bf8d7b1f4add7c3c58a1bfe96491528.

**Comment by AnderUstarroz** [comment]
Something strange in your last commit Jason.  I've reinstalled **aiopyramid** package removing the .pip cache:
```
pip install --upgrade --no-deps --force-reinstall --ignore-installed aiopyramid
```
But the file "**aiopyramid/gunicorn/worker.py**" updated on commit [[feb104c](https://github.com/housleyjk/aiopyramid/commit/feb104cd0bf8d7b1f4add7c3c58a1bfe96491528)] doesn't seems to be updated. Just have a look at the [pypi-aiopyramid page](https://pypi.python.org/pypi/aiopyramid/0.3.0), if you download manually the file **aiopyramid-0.3.0.tar.gz** you will see that the file "**aiopyramid/config.py**" was correctly updated but "**aiopyramid/gunicorn/worker.py**" wasn't.

**Comment by housleyjk** [comment]
Hi Ander,

I haven't updated pypi yet. The fixes are only to the latest development
version of aiopyramid. To get the changes you need to uninstall aiopyramid
then install from git.

pip uninstall aiopyramid

pip install git+git://github.com/housleyjk/aiopyramid

That should do it for you.

Good luck,

Jason

2015-01-21 6:46 GMT-07:00 Ander <notifications@github.com>:
