### ISSUE TITLE
Class methods which are Synchronized coroutines cannot be called more than once per instance

### ISSUE THREAD

**Issue by AnderUstarroz** [housleyjk/aiopyramid#9]
Hi Boss,
I've been playing around and I've noticed a strange behavior or an architecture limitation. Seems that the  class methods  which are synchronized coroutines cannot be called more than once per instance. That was a hell of a phrase I know ;) 
let me show you the code:

```
from aiopyramid.helpers import spawn_greenlet, synchronize


@view_config(route_name='test')
def test(request):
    result = yield from spawn_greenlet(step_1)
    return Response(result)

#Step_1: Normal function calling a normal class
def step_1():
    return A().run()

#class A: Class instantiating the class B and calling twice his synchronized coroutine method
class A():
    def run(self):
        b = B()
        b1 = b.get_url()
        b2 = b.get_url() #This is the cabron!
        return b1 + b2

#class B: Class with a synchronized coroutine
class B():
    @synchronize
    @asyncio.coroutine
    def get_url(self):
        yield from asyncio.sleep(1)
        return 'B class result!'
```
This code throws ```AttributeError: 'str' object has no attribute 'getURL'```
Nevertheless if I amend the class A to use different instances of class B it seems to work fine:
```
#class A: Executes get_url() using two different instances of class B
class A():
    def run(self):
        b1 = B().get_url()
        b2 = B().get_url()
        return b1 + b2
```
Is this a limitation of the architecture? this could be a real pain in the ass when rewriting other libraries. Cause we will have to multiply instances just for calling a single method.

**Comment by housleyjk** [comment]
Hi Ander,

Thanks for finding this. A synchronized coroutine should definitely be callable multiple times (barring other modifications.) Sadly I was not able to replicate this issue. I modified the example code removing the pyramid dependencies and it worked fine.

``` python
import asyncio

from aiopyramid.helpers import spawn_greenlet, synchronize


@asyncio.coroutine
def test():
    print('starting coroutine')
    result = yield from spawn_greenlet(step_1)
    print('finished coroutine ', result)
    return result


# Step_1: Normal function calling a normal class
def step_1():
    print('in step 1')
    return A().run()


# class A: Class instantiating the class B and calling twice his synchronized coroutine method
class A:
    def run(self):
        print('in A run')
        b = B()
        print('made b', b)
        b1 = b.get_url()
        print('called get_url once', b1)
        b2 = b.get_url()  # This is the cabron!
        print('called get_url twice', b2)
        return b1 + b2


# class B: Class with a synchronized coroutine
class B:
    @synchronize
    @asyncio.coroutine
    def get_url(self):
        yield from asyncio.sleep(1)
        return 'B class result!'

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

You should be able to run this as an independent module (e.g `synchrobug.py`). The output I get for `python synchrobug.py`:

```
starting coroutine
in step 1
in A run
made b <__main__.B object at 0x7fead3ad44e0>
called get_url once B class result!
called get_url twice B class result!
finished coroutine  B class result!B class result!
```

That's just what we would expect if it were working correctly. Can you give me an example within a web application? I am thinking this bug is due to some interaction between `aiopyramid` and `pyramid`.

**Comment by AnderUstarroz** [comment]
You are right, it's due to some interaction between **aiopyramid** and **pyramid**. But I cannot tell exactly where, I'm getting lost with so many wrappers. You should be able to replicate  the issue just coping my code in a basic view and adding ```config.add_route('test', '/')``` to the **\_\_init\_\_.py**
I'm using gunicorn by the way. Have you tried with uwsgi?

**Comment by housleyjk** [comment]
I just tried with gunicorn, and I didn't have any troubles. The only change to the code I made was to add `@view_config(context=Root, renderer='aiotutorial:templates/home.jinja2')` (I have a traversal based app I am using to make a tutorial). Anyway my output was:

```
gunicorn --paste development.ini --reload                                                                                                                            master 
2015-02-12 13:58:46,522 INFO  [gunicorn.error][MainThread] Starting gunicorn 19.2.0
2015-02-12 13:58:46,529 INFO  [gunicorn.error][MainThread] Listening at: http://0.0.0.0:6543 (7809)
2015-02-12 13:58:46,529 INFO  [gunicorn.error][MainThread] Using worker: aiopyramid.gunicorn.worker.AsyncGunicornWorker
2015-02-12 13:58:46,531 INFO  [gunicorn.error][MainThread] Booting worker with pid: 7813
starting coroutine
in step 1
in A run
made b <aiotutorial.views.B object at 0x7fa3e98b24e0>
called get_url once B class result!
called get_url twice B class result!
finished coroutine  B class result!B class result!
2015-02-12 13:58:54,276 INFO  [gunicorn.access][MainThread] 127.0.0.1 - - Thu, 12 Feb 2015 20:58:54 GMT "GET / HTTP/1.1" 200 2416 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
```

**Comment by housleyjk** [comment]
I tried it again with uwsgi and it worked for me again. I hope you can send me more details because this is definitely an important issue, and I want to get you unstuck on your project too :).

**Comment by AnderUstarroz** [comment]
I've  just created a new fresh version of your aiopyramid example and added the conflicting code. But still getting the same error: 
```
File "/Projects/test_aiopyramid/test_aiopyramid/views.py", line 24, in run
    d = c.getURL()
AttributeError: 'str' object has no attribute 'getURL'
```

These are all the steps to replicate the error:
- First I've created a new Virtual environment with **Python 3.4.2**
- Setup the new project:
```
pip install aiopyramid gunicorn
pcreate -s aio_starter test_aiopyramid
cd test_aiopyramid
python setup.py develop
```
After the setup I've just copied this code in the file **test_aiopyramid/test_aiopyramid/view.py**:
```
import asyncio

from pyramid.view import view_config
from aiopyramid.helpers import spawn_greenlet, synchronize


@view_config(route_name='say_hello', renderer='string')
def say_hello(request):
    out = yield from spawn_greenlet(step_1)
    return Response(out)

def step_1():
    return A().run()

class A():
    def run(self):
        a = B().run()
        return a

class B():
    def run(self):
        c =C()
        c = c.getURL()
        d = c.getURL()
        return c + d

class C():
    @staticmethod
    @synchronize
    @asyncio.coroutine
    def getURL():
        yield from asyncio.sleep(2)
        return '(C class)'
```
This is the pip list of packages & versions
```
aiohttp (0.14.4)
aiopyramid (0.3.1)
greenlet (0.4.5)
gunicorn (19.2.1)
PasteDeploy (1.5.2)
pip (1.5.6)
pyramid (1.5.2)
repoze.lru (0.6)
setuptools (3.6)
test-aiopyramid (0.0)
translationstring (1.3)
venusian (1.0)
WebOb (1.4)
websockets (2.4)
zope.deprecation (4.1.2)
zope.interface (4.1.2)
```
Let me know how it goes, if it works for you after following all this steps and using same versions... I'll get into the toilet and flush me away.

**Comment by housleyjk** [comment]
Great! It looks like it has something to do with with staticmethod decorator. I will investigate.

**Comment by housleyjk** [comment]
Wait, I looked closer at your code. You are reassigning `c` to the output of `getURL`, so of course you can't call get url on the string `c`. 

```python
class B():
    def run(self):
        c =C()
        c = c.getURL()  # here c becomes '(C class)' from getURL
        d = c.getURL()  # c has no method getURL because it is a str
        return c + d
```

If you fix the variable reassignment, the staticmethod works fine. Please verify that this is the bug and I will close the issue.

**Comment by AnderUstarroz** [comment]
[ohh god...](http://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Paris_Tuileries_Garden_Facepalm_statue.jpg/300px-Paris_Tuileries_Garden_Facepalm_statue.jpg) go ahead and close it, that was extremely stupid. Please don't tell this to your children...

**Comment by housleyjk** [comment]
No problem. Every Python dev has done that before. That's why languages like [rust](http://www.rust-lang.org/) force programmers to specify mutable vs immutable variables. I'm just glad that synchronize works with staticmethods. It's an edge case but certainly one I want to support.

**Comment by AnderUstarroz** [comment]
Thanks for being so nice! haha your code is so good that I have to make up fake issues ;)
